version: "3"

services:
  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123 -queue "projects/project-id/locations/location/queues/foo-queue"
    ports:
      - "${TASKS_PORT:-8123}:8123"
